
platform :ios, '7.0'
use_frameworks!

source 'https://github.com/EmptyOps/objective_c_sqlite_helper.git'
target 'objective_c_sqlite_helper_Example' do
    
    pod 'objective_c_sqlite_helper', :path => '~/Documents/Classes/objective_c_sqlite_helper'
    
    target 'objective_c_sqlite_helper_Tests' do
        inherit! :search_paths
    end
    
end


